apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-personas-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.personas.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-personas-service
            port:
              number: 80
